### ISSUE TITLE
Original BIOASQ dataset

### ISSUE THREAD

**Issue by fj-morales** [nlpaueb/deep-relevance-ranking#5]
Hi, I am working with your model and BIOASQ dataset. Could you please provide the links for the original corpus, the one with the 18M or 28M documents, please?

**Comment by fj-morales** [comment]
I understand the original data comes from https://www.nlm.nih.gov/databases/download/pubmed_medline.html and you used the Pubmed 2018 Baseline. Could you confirm if you also included articles published in 2018?

**Comment by gbrokos** [comment]
Hi, indeed we used the Pubmed 2018 Baseline and specifically the January 2018 dump. As I recall there was a relatively small number of articles published in 2018. Unfortunately, 2018 Baseline has now been replaced by the 2019 baseline so I cannot provide you with a link for the exact set of documents. However, I could upload the pmids of the articles that we used, probably tommorow. Would this help?

**Comment by fj-morales** [comment]
Hi, yes. Actually, could you send the PMIDs from the 17.7M articles resulting after filtering the one with no Title? 
Thanks in advanced.

**Comment by gbrokos** [comment]
Sure.

**Comment by gbrokos** [comment]
The PMIDs of the 17,730,230 articles (title and abstract) that we used, are listed in the following file:

[https://archive.org/download/deep_relevance_ranking_data/PMIDs.txt](https://archive.org/download/deep_relevance_ranking_data/PMIDs.txt)
